[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=A9D5BA3849EE9F1DE7095D9BD98D0412
ProjectName=Third Person Game Template

[/Script/UnrealEd.ProjectPackagingSettings]
MapsToCook=(FilePath="/Game/MyStuff/MainLevel")
Build=IfProjectHasCode
BuildConfiguration=PPBC_Shipping
FullRebuild=True
IncludePrerequisites=True
IncludeAppLocalPrerequisites=True
ApplocalPrerequisitesDirectory=(Path="$(EngineDir)/Binaries/ThirdParty/AppLocalDependencies")
IncludeCrashReporter=True
bCompressed=True
bUseIoStore=True
bUseZenStore=False
+DirectoriesToAlwaysCook=(Path="/Game/YanLi")

[/Script/Engine.AssetManagerSettings]
; 修复: 资产管理器缺少GameFeatureData类型条目，导致游戏功能插件无法正常工作
+PrimaryAssetTypesToScan=(PrimaryAssetType="GameFeatureData",AssetBaseClass=/Script/GameFeatures.GameFeatureData,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game")))
